apiVersion: v1
kind: Service
metadata:
  name: wls-medrec
  labels:
    app: wls-medrec
    visualize: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 7011
      targetPort: 7011
  selector:
    app: wls-medrec

