apiVersion: v1
kind: Service
metadata:
  name: as # Headless Service to enable stable DNS name for AdminServer StatefulSet
spec:
  ports:
  - port: 7001
    targetPort: 7001
  clusterIP: None
  selector:
    app: as
---
apiVersion: v1
kind: Service
metadata:
  name: as-console # Service to access WLS Console
spec:
  ports:
  - port: 7001
    targetPort: 7001
  type: LoadBalancer
  selector:
    app: as
---
apiVersion: v1
kind: Service
metadata:
  name: as-admin # Service for WLST clients over custom WLS network channel
spec:
  ports:
  - port: 7011
    targetPort: 7011
  type: LoadBalancer
  selector:
    app: as
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: as
spec:
  serviceName: "as"
  replicas: 1
  template:
    metadata:
      labels:
        app: as
        visualize: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: as
        image: srivar/wls-12212-cluster
        ports:
        - name: listen-port
          containerPort: 7001
        - name: ext-admin-port # custom network channel for WLST traffic
          containerPort: 7011
