apiVersion: v1
kind: Service
metadata:
  name: wls-jms
spec:
  ports:
  - port: 7001
    targetPort: 7001
  clusterIP: None # Headless Service to enable stable DNS names for StatefulSet Pods
  selector:
    app: wls-jms
---
apiVersion: v1
kind: Service
metadata:
  name: wls-jms-console # Service to access WLS Console
spec:
  ports:
  - port: 7001
    targetPort: 7001
  type: LoadBalancer
  selector:
    app: wls-jms
---
apiVersion: v1
kind: Service
metadata:
  name: wls-jms-admin # Service for WLST clients over custom WLS network channel
spec:
  ports:
  - port: 7011
    targetPort: 7011
  type: LoadBalancer
  selector:
    app: wls-jms
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: wls-jms
spec:
  serviceName: "wls-jms"
  replicas: 1
  template:
    metadata:
      labels:
        app: wls-jms
        visualize: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: wls-jms
        image: srivar/wls-12212
        ports:
        - name: listen-port
          containerPort: 7001
        - name: ext-admin-port  # custom network channel for WLST traffic
          containerPort: 7011
        volumeMounts:
        - name: test-volume
          mountPath: /data/filestores # Persistent JMS Store
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: pvc1
