apiVersion: v1
kind: Service
metadata:
  name: wls-legacy
  labels:
    app: wls-legacy
    visualize: "true"
spec:
  type: NodePort
  ports:
    - port: 7001
      targetPort: 7001
  selector:
    app: wls-legacy
